# Generated by Django 3.0.7 on 2020-06-15 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_assetlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('account_number', models.CharField(default='-', max_length=24)),
                ('sequense', models.IntegerField()),
                ('isAsset', models.IntegerField(default=1)),
                ('live', models.IntegerField(default=1)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki', models.IntegerField(default=0)),
                ('account_type', models.CharField(choices=[('管理費会計', '管理費会計'), ('修繕費会計', '修繕費会計'), ('駐車場会計', '駐車場会計')], max_length=16)),
                ('asset', models.BigIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset_list.Master_assetlist')),
            ],
        ),
    ]
