# Generated by Django 3.1 on 2020-09-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlist',
            name='account_type',
            field=models.CharField(choices=[('管理費会計', '管理費会計'), ('修繕費会計', '修繕費会計'), ('駐車場会計', '駐車場会計'), ('保険対応', '保険対応')], max_length=16),
        ),
    ]
