# Generated by Django 3.1.5 on 2021-02-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_list', '0002_auto_20200913_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_assetlist',
            name='live',
        ),
        migrations.AddField(
            model_name='master_assetlist',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
