# Generated by Django 3.0.7 on 2020-07-05 01:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spending_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='支出日')),
                ('name', models.CharField(max_length=64, verbose_name='支出名')),
                ('expense_item', models.CharField(choices=[('交通費', '交通費'), ('消耗品', '消耗品'), ('文房具', '文房具'), ('雑費', '雑費')], default='none', max_length=32, verbose_name='費目')),
                ('expense', models.IntegerField()),
                ('comment', models.TextField(verbose_name='摘要')),
            ],
        ),
    ]
