# Generated by Django 3.0.7 on 2020-07-05 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_subject',
            name='spending_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='支出日'),
        ),
    ]
