# Generated by Django 3.0.7 on 2020-07-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20200705_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_subject',
            name='expense',
            field=models.IntegerField(verbose_name='支出額'),
        ),
        migrations.AlterField(
            model_name='account_subject',
            name='spending_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='日付'),
        ),
    ]
