# Generated by Django 3.0.8 on 2020-07-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0004_auto_20200705_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_subject',
            name='expense_item',
            field=models.CharField(choices=[('交通費', '交通費'), ('消耗品', '消耗品'), ('文房具', '文房具'), ('組合運営費', '組合運営費'), ('雑費', '雑費')], default='none', max_length=32, verbose_name='費目'),
        ),
    ]
