# Generated by Django 3.0.8 on 2020-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20200713_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_subject',
            name='expense_item',
            field=models.CharField(choices=[('交通費', '交通費'), ('通信費', '通信費'), ('消耗品', '消耗品'), ('事務用品', '事務用品'), ('図書費', '図書費'), ('組合運営費', '組合運営費'), ('雑費', '雑費')], default='none', max_length=32, verbose_name='費目'),
        ),
        migrations.AlterField(
            model_name='account_subject',
            name='name',
            field=models.CharField(max_length=64, verbose_name='科目名'),
        ),
    ]
