# Generated by Django 3.0.8 on 2020-07-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0006_auto_20200725_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_subject',
            name='expense_item',
            field=models.CharField(choices=[('交通費', '交通費'), ('通信費', '通信費'), ('消耗品', '消耗品'), ('事務用品', '事務用品'), ('図書費', '図書費'), ('組合運営費', '組合運営費'), ('雑費', '雑費'), ('収入', '収入')], default='none', max_length=32, verbose_name='費目'),
        ),
    ]
