# Generated by Django 3.0.8 on 2020-07-26 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_auto_20200726_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='none', max_length=32, verbose_name='費目名')),
            ],
        ),
        migrations.AddField(
            model_name='account_subject',
            name='expense_item2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cashier.ExpenseItem'),
        ),
    ]
