# Generated by Django 3.0.8 on 2020-07-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_auto_20200726_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_subject',
            name='expense_item',
        ),
    ]
