# Generated by Django 3.0.8 on 2020-07-26 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0009_remove_account_subject_expense_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_subject',
            old_name='expense_item2',
            new_name='expense_item',
        ),
    ]
