# Generated by Django 3.0.7 on 2020-06-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki', models.IntegerField()),
                ('account_type', models.CharField(choices=[('管理費会計', '管理費会計'), ('修繕費会計', '修繕費会計'), ('駐車場会計', '駐車場会計')], max_length=16)),
                ('cost', models.BigIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
