# Generated by Django 3.1.7 on 2021-02-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_out', '0003_parking_expenditure_koujimei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_expenditure',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
