# Generated by Django 3.1.7 on 2021-03-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_out', '0004_auto_20210227_0818'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parking_expenditure',
            constraint=models.UniqueConstraint(fields=('ki', 'account_type'), name='parking_out_unique'),
        ),
    ]
