# Generated by Django 3.1.7 on 2021-04-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset_list', '0005_auto_20210404_1518'),
        ('parking_out', '0005_auto_20210307_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_expenditure',
            name='account_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset_list.accounttype'),
        ),
    ]
