# Generated by Django 3.0.7 on 2020-06-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_shuuzenhi_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Shuuzenhi_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki', models.IntegerField()),
                ('income', models.BigIntegerField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shuuzenhi_in.Master_shuuzenhi_income')),
            ],
        ),
    ]
