# Generated by Django 3.1.5 on 2021-02-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuuzenhi_in', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_shuuzenhi_income',
            name='alive',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
