# Generated by Django 3.1.5 on 2021-02-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuuzenhi_in', '0002_master_shuuzenhi_income_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='shuuzenhi_income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_shuuzenhi_income',
            name='alive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
