# Generated by Django 3.1.7 on 2021-03-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuuzenhi_in', '0004_auto_20210307_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_shuuzenhi_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='master_shuuzenhi_income',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shuuzenhi_in.category_shuuzenhi_income'),
        ),
    ]
