# Generated by Django 3.0.7 on 2020-06-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki', models.IntegerField(unique=True)),
                ('parking_lot_income', models.BigIntegerField(default=0)),
            ],
        ),
    ]
