# Generated by Django 3.1.7 on 2021-02-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_in', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_parking_income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='parking_income',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parking_in.master_parking_income'),
        ),
    ]
