# Generated by Django 3.1.7 on 2021-03-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_in', '0002_auto_20210227_2104'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parking_income',
            constraint=models.UniqueConstraint(fields=('ki', 'master'), name='parking_in_unique'),
        ),
    ]
