# Generated by Django 3.1.7 on 2021-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanrihi_in', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanrihi_income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
