# Generated by Django 3.0.7 on 2020-06-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Master_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('sequense', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kanrihi_out.Master_category')),
            ],
        ),
        migrations.CreateModel(
            name='Kanrihi_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ki', models.IntegerField()),
                ('expense', models.BigIntegerField()),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kanrihi_out.Master_expense')),
            ],
        ),
    ]
