# Generated by Django 3.1.7 on 2021-03-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanrihi_out', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kanrihi_expense',
            constraint=models.UniqueConstraint(fields=('ki', 'master'), name='kanrihi_out_unique'),
        ),
    ]
