# Generated by Django 3.1.7 on 2021-03-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuuzenhi_out', '0002_auto_20200913_0616'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rireki',
            new_name='Shuuzenhi_expense',
        ),
    ]
